name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: ⎔ Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.x

    - name: 🔎 Setup Git User
      shell: bash
      run: |
        git config --global user.email "thinh.duc.trinh@gmail.com"
        git config --global user.name "Trinh Duc Trinh"

    - name: 📥 Download deps
      shell: bash
      run: |
        corepack enable
        yarn install --frozen-lockfile