import fs from "node:fs/promises";
import path from "node:path";
import { type RequiredBrifUIPluginConfig } from "@brifui/theme";

export const generateThemeConfig = async (
  config: RequiredBrifUIPluginConfig
) => {
  await fs.mkdir(config.themeFile.dir, { recursive: true });
  await fs.writeFile(
    path.resolve(config.themeFile.dir, config.themeFile.name),
    `
/**
 * This file is automatically generated by @brifui/cli
 * NOTE: DO NOT MODIFY THIS FILE MANUALLY
 */
export const theme = ${JSON.stringify(config)};
    `
  );
};
