import fs from "node:fs/promises";

export const generateThemeTypes = async ({ output }: { output: string }) => {
  await fs.writeFile(
    output,
    `
/**
 * This file is automatically generated by @brifui/cli
 * NOTE: DO NOT MODIFY THIS FILE MANUALLY
 */

import {
  BorderRadiusConfig,
  BreakpointConfig,
  ColorConfig,
  ShadowConfig,
  SpacingConfig
} from "@brifui/theme";

declare global {
  interface BrifUIThemeConfig {
    colors: {
      ref?: Record<string, ColorConfig>;
      sys?: Record<string, ColorConfig>;
    };
    breakpoints: BreakpointConfig;
    spacing: SpacingConfig;
    borderRadius: BorderRadiusConfig;
    shadow: ShadowConfig;
  }

  type BrifUIThemeKey = "light" | "dark" | "violet";
}

export {};
    `
  );
};
