import fs from "node:fs/promises";
import { type RequiredBrifUIPluginConfig } from "@brifui/theme";

const template = (_config: RequiredBrifUIPluginConfig) => `
/**
 * This file is automatically generated by @brifui/cli
 * NOTE: DO NOT MODIFY THIS FILE MANUALLY
 */

declare module "@brifui/theme/types" {
  import { FlattenedColorKey } from "@brifui/theme";
  
  export type BrifUIThemeConfig = typeof import("../theme").theme;

  export type BrifUIThemeKey = keyof BrifUIThemeConfig["themes"];
  export type FlattenSysColorKey = FlattenedColorKey<
    BrifUIThemeConfig["base"]["colors"]["sys"]
  >;
  export type ComponentColor = keyof BrifUIThemeConfig["base"]["colors"]["sys"];
}
`;

export const generateThemeTypes = async ({
  config,
  output
}: {
  config: RequiredBrifUIPluginConfig;
  output: string;
}) => {
  await fs.writeFile(output, template(config));
};
