export const EXCEPTION_CODE = {
  STYLED_PACKAGE_NOT_FOUND: "STYLED_PACKAGE_NOT_FOUND",
  CODEGEN_FAILED: "CODEGEN_FAILED",
  CODEGEN_TRANSPILE_FAILED: "CODEGEN_TRANSPILE_FAILED"
};

export const EXCEPTIONS = {
  StyledPackageNotFound: new Error(EXCEPTION_CODE.STYLED_PACKAGE_NOT_FOUND),
  CodegenFailed: new Error(EXCEPTION_CODE.CODEGEN_FAILED),
  CodegenTranspileFailed: new Error(EXCEPTION_CODE.CODEGEN_TRANSPILE_FAILED)
};
