import { existsSync, mkdirSync, writeFile } from "node:fs";
import path from "node:path";

import { BrifUIPluginConfig, ColorConfig, DeepRequired } from "../../types";
import { BreakpointConfig } from "../../types/breakpoints";

const DIR = ".brifui";
const FILENAME = `${DIR}/brif-types.d.ts`;
const THEME_FILENAME = `${DIR}/theme.ts`;

const generateBreakpointTypes = (bp: BreakpointConfig = {}) => {
  return `breakpoints: BreakpointConfig<{
      ${Object.keys(bp)
        .map((breakpoint) => `${JSON.stringify(breakpoint)}: string;\n`)
        .join("")}
    }>`;
};

const generateColorTypes = (
  colors: Record<string, ColorConfig> = {},
  tier?: "ref" | "sys"
) => {
  return `${tier === "ref" ? "ExtendRefColors" : "ExtendSysColors"}<{${Object.keys(
    colors
  )
    .map((color) => {
      const colorValue = colors[color];
      if (typeof colorValue === "string")
        return `${JSON.stringify(color)}: string;\n`;
      else if (typeof colorValue === "object") {
        return `${JSON.stringify(color)}: {
        ${Object.keys(colorValue)
          .map((shade) => `${JSON.stringify(shade)}: string;\n`)
          .join("")}
        };\n`;
      }
      return `${JSON.stringify(color)}: never;\n`;
    })
    .join("")}}>;`;
};

export const generateTypes = async (configs: BrifUIPluginConfig) => {
  return new Promise((res, rej) => {
    const { breakpoints, colors: { sys = {}, ref = {} } = {} } =
      configs.base || {};

    if (!existsSync(path.resolve(process.cwd(), DIR))) {
      mkdirSync(path.resolve(process.cwd(), DIR));
    }
    writeFile(
      path.resolve(process.cwd(), FILENAME),
      `/**
 * This file is auto-generated by \`@brifui/theme\`.
 * NOTE: DO NOT MODIFY THIS FILE MANUALLY
 */
import { BreakpointConfig, ExtendRefColors, ExtendSysColors } from "@brifui/theme";

declare module "@brifui/theme" {
  export interface BrifUIThemeConfig {
    colors: {
      ref: ${generateColorTypes(ref, "ref")}
      sys: ${generateColorTypes(sys, "sys")}
    },
    ${generateBreakpointTypes(breakpoints)};
  };
}
`,
      (err) => {
        if (err) rej(err);
        else res(void 0);
      }
    );
  });
};

export const generateThemeFile = async (
  configs: DeepRequired<BrifUIPluginConfig>
) => {
  return new Promise((res, rej) => {
    if (!existsSync(path.resolve(process.cwd(), DIR))) {
      mkdirSync(path.resolve(process.cwd(), DIR));
    }
    writeFile(
      path.resolve(process.cwd(), THEME_FILENAME),
      `/**
 * This file is auto-generated by \`@brifui/theme\`.
 * NOTE: DO NOT MODIFY THIS FILE MANUALLY
 */
export const theme  = ${JSON.stringify(configs)};
`,
      (err) => {
        if (err) rej(err);
        else res(void 0);
      }
    );
  });
};
