name: Release

permissions:
  actions: write
  pull-requests: write
  contents: write

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install
      
      - name: Create Release Pull Request or Publish to NPM registry
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          title: "ci(changesets): :package: version packages"
          commit: 'ci(changesets): version packages'
          setupGitUser: false
        env:
          # GITHUB_TOKEN is required for creating a pull request and will be provided by the Github Action automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN is required for publishing to registry and needs to be provided manually
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Release
        if: steps.changesets.outputs.published != 'true'
        timeout-minutes: 15
        run: |
          yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
