name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Build packages
        run: yarn build
      
      - name: Test
        run: yarn test